Require base >= 4.11
With older versions, GHC reports errors like:

    src/Opts.hs:30:23: error:
        • Variable not in scope:
            (<>) :: Mod f15 a14 -> Mod f16 a15 -> Mod ArgumentFields String
        • Perhaps you meant one of these:
            ‘<$>’ (imported from Options.Applicative),
            ‘<*>’ (imported from Options.Applicative),
            ‘*>’ (imported from Options.Applicative)
       |
    30 |                       <> help "command to run" )
       |                       ^^